### ISSUE TITLE
Question about code and dataset

### ISSUE THREAD

**Issue by tungts1101** [mariusbock/wear#1]
I really appreciate your team's work, but may I ask do you have a timeline for publishing the dataset?

**Comment by mariusbock** [comment]
Hi, thank you for the feedback! The dataset page will go live this within the next few days. I will let you know in this thread then.

**Comment by mariusbock** [comment]
Hi, the data is now available via https://bit.ly/wear_dataset

The code will be provided in the next few days!

**Comment by mariusbock** [comment]
Hi, the code to reproduce experiments is now released.
