### ISSUE TITLE
Request for GoPro IMU data

### ISSUE THREAD

**Issue by Peipi98** [mariusbock/wear#2]
Hello everyone!

In EPIC-Kitchens there are IMU data extracted from GoPro videos by leveraging [this tool](https://github.com/JuanIrache/gopro-telemetry). Is it possible to extend your dataset with them in order to have also head IMU informations?

Thank you!

**Comment by mariusbock** [comment]
Hi, unfortunately we did not extract the IMU data of the camera. I recommend you using methods which estimate the head movement based on egocentric video data. If you are planning of participating in the WEAR Challenge: Note that there will be no video data provided for the test set of the WEAR challenge.

**Comment by Peipi98** [comment]
Thanks for your reply :)
