### ISSUE TITLE
frames and stride

### ISSUE THREAD

**Issue by Peipi98** [mariusbock/wear#3]
Hi!

I was wondering what's the meaning behind {frames}frames_{stride}stride folders in the data creation pipeline.

It's clear to me that the videos have been recorded at 60fps, but I'm missing the meanings of frames and stride, especially when frames are 120. I've checked both paper, supplementary materials and the [data creation pipeline](https://github.com/mariusbock/wear/tree/main/data_creation), but I've seen that frames and strides have been used to give a name to the files only. Also, how are they related to IMU features?

Am I missing something?

**Comment by mariusbock** [comment]
The meaning behind frames and stride refers to the clip length employed during the benchmark experiments detailed in the WEAR paper. We tested three clip lengths: 0.5 seconds (30 frames), 1 second (60 frames) and 2 seconds (120 frames). The same "clip lengths" are also applied to the inertial data, i.e. the three clip/ sliding windows tested were: 0.5 seconds (25 samples), 1 second (50 samples) and 2 seconds (100 samples). All sliding windows/ clips had an overlap of 50% with the next window/ clip. To answer your question: the folder structure thus follows the video data notation.

**Comment by Peipi98** [comment]
thanks!
