### ISSUE TITLE
`eval_type` parameter

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [mariusbock/wear#5]
Hello, I would like to inquire about the `eval_type` parameter in `main.py`, which has two types: `split` and `loso`. What are the specific differences between them?

**Comment by mariusbock** [comment]
The eval_type parameter currently has no function. The repository currently only supports the split-evaluation with a 6-6-6 split. Leave-One-Subject-Out evaluation will be added at a later point. Hope this helps!

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
Thank you for your answer!
