### ISSUE TITLE
Consultation on reproducing results

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [mariusbock/wear#6]
![image](https://github.com/mariusbock/wear/assets/86902247/96566951-07fb-4511-bb22-73d6f7aeee0a)
instructions：nohup python -u main_linux.py --config ./configs/30_frames_15_stride/deepconvlstm_long.yaml --seed 1 --eval_type split > exp1.log 2>&1 &

main.py：
![image](https://github.com/mariusbock/wear/assets/86902247/32a90e47-a921-4195-a900-a49a1789762c)

**Comment by mariusbock** [comment]
The results need to be postprocessed. Without applying the majority filter (see postprocessing/majority_fil.py) the mAP scores of the inertial models will be near zero due to frequently happening one-off mispredictions (ultimately splitting segments). Hope this helps!

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
Okay, thank you very much for your answer and your work support. I will now debug majority_fil. py

**Comment by Peipi98** [comment]
Hello, I've checked the [instructions](https://github.com/mariusbock/wear/blob/main/postprocessing/README.md), but if oracle, camera and inertial are clear to me, the combined approach in early fusion isn't. If I've correctly understood, the early fusion approaches has to be treated as well as the vision based, by using `score_thresh.py`: am I right or did you use another approach?

**Comment by mariusbock** [comment]
Yes you are correct. The early-fusion experiments were only performed with the Temporal Action Localization models (Tridet and ActionFormer). Hence, we have to apply score thresholding like we do in the vision-based experiments

**Comment by Peipi98** [comment]
thanks!
