### ISSUE TITLE
I want to konw where afunction  is 

### ISSUE THREAD

**Issue by fangyu05** [mariusbock/wear#8]
I want to know where the method called num_1D_cpu is, because when I downloaded the entire code repository, it showed that I couldn't find this method. I tried to reference it by downloading the mmcv repository, but failed.
![1](https://github.com/user-attachments/assets/2f6afe63-af20-49e8-a418-144f4e3d769e)

**Comment by mariusbock** [comment]
Hi, you need to compile the C++ implementation of NMS for each vision-based model separately. Please check the INSTALL.md for instructions (bottom part of the ReadMe).

**Comment by fangyu05** [comment]
> Hi, you need to compile the C++ implementation of NMS for each vision-based model separately. Please check the INSTALL.md for instructions (bottom part of the ReadMe).

Ok, I will try it. Thanks!!
