### ISSUE TITLE
Run Errors

### ISSUE THREAD

**Issue by fangyu05** [mariusbock/wear#9]
Why did this error occur？Help me!
![2](https://github.com/user-attachments/assets/e9f49ef0-0a07-4659-87ff-098145a906a5)

**Comment by mariusbock** [comment]
Hi, my best guess is that it has to do with your operating system (Windows) and the one I developed the repository with (Linux). There seems to be an error when creating directories (os.makedirs(dir_path)). Maybe check how you would need to alter that line such that it works with Windows.

**Comment by mariusbock** [comment]
Maybe this stackoverflow post helps you: https://stackoverflow.com/questions/17619079/python-why-does-os-makedirs-cause-windowserror/29433918

**Comment by fangyu05** [comment]
Thanks very much. I will try to solve it with this post!

**Comment by fangyu05** [comment]
I‘m sorry to say that i have a new problem which is also a run error. I  don't konw why the problem occurs.
![image](https://github.com/user-attachments/assets/8ae95dbd-5ead-4227-bece-f8d6498b06f9)
![image](https://github.com/user-attachments/assets/1fbb6699-b6ae-423b-aaac-9942ceb63039)

**Comment by fangyu05** [comment]
I really want to konw why i can't found this path, because i print the path which is obtained  in order to contrast the correct real path. It has been proven that these two paths are consistent, so I really don't understand where the key to the problem lies.

**Comment by fangyu05** [comment]
Oh no, I did it! May be the prooblem  is i download a incorrect package. Now i can run it!
![image](https://github.com/user-attachments/assets/45631180-76e8-411d-b9da-7be087874088)
